export const BLOCKED_LANGUAGES = [
    '\\p{Cyrillic}',
    '\\p{Arabic}',
    '\\p{Hiragana}',
    '\\p{Greek}',
    '\\p{Hebrew}',
    '\\p{Hangul}',
    '\\p{Han}'
  ]
  
  export const mandarin = [
    '\\p{Han}'
  ]
  
  export const ONEWORD = ['è', 'ç', 'ğ', 'é', 'à', 'â', 'ê', 'î', 'û', 'ê', 'ö', 'ë', 'ä', 'ñ', 'ú', '¿', 'á', 'ü',
    'ş', 'é', 'å', 'ó', 'ò', 'ᝧ']
  
  export const BLOCKED_WORDS = ['nigger', 'jews', 'retarded', 'Kurvva']
  
  export const ONE = ['wyjebalo', 'azizam', 'anashe', 'ankara', 'bazdmeg', 'culiao', 'chiquita', 'he does is smurf to win', 'perder', 'incel', 'incest', 'autist', 'cuando', 'GAMISETA', 'duermes', 'gei', 'yaytınlar', 'oiggers', 'tits',]
  export const onemap = [];
  export const FLAME = [
    'you suck',
    'fuck',
    // 'top gap',
    'stop tilting',
    'you are so tilted',
    'you are tilted',
    'blame',
    // 'top diff',
    'unfollow',
    'ترول نووب سگ',
    'نشط:',
    'penis',
    //'cock',
    'C0ck',
    'cunt',
    'you are dogshit',
    //'dogs',
    'complain',
    'c0cks',
    'cocks',
    'stop inting',
    'stop playing.',
    'dating',
    'go cry',
    'stop crying',
    'so mad',
    'boosted',
    //'sad',
    'pussy',
    'trash',
    'piss',
    //'bad',
    'raging',
    'idiot',
    'shut up',
    'fucking',
    'you are so bad',
    'bullying',
    'bully',
    'you are cringe',
    'he sucks',
    'TOXICBLADE',
    'stop losing',
    'ruin',
    'whine',
    'mental',
    'you are inting',
    'so toxic',
    'grief',
    'griefing',
    'abusing',
    //'top dif',
    'you are so cringe',
    'hardstuck',
    'hardstucks',
    'u inted',
    'chill',
    'dikk',
    'fck',
    'getting carried',
    'cringey loser',
    'you bad',
    'stop complaining',
    'so insecure',
    'flame teammates',
    'p*ssy',
    'dicked',
    'REKT BY GOLD',
    'StuckBlade',
    'how is this guy rank 1',
    'toxic wtf',
    'being toxic',
    'u suck',
    'crying',
    'me int',
    'cryin',
    'flaming',
    'toxic man',
    'u lose',
    'too big of an ego',
    'fkn',
    'is cry',
    'excuses',
    'griefin',
    'why is it always junglers fault',
    'always feeding',
    'you literally feed',
    'Ur mom',
    'nuts?',
    'you are that bad',
    'wtf is wrong with u',
    'u cry',
    'babycries',
    'stop complaining',
    'ur fault',
    'raging',
    'blaming jg',
    'JUST BAD',
    'blames tea',
    'Stop screaming',
    'you scream like the children',
    'YOURMOM',
    'ur playing so bad',
    'DONT CRY',
  ]
  export const ONEFLAME = ['bitch', 'Suk', 'screeching',
  ]
  
  export const Korean = [
    '\\p{Hangul}',
  ]